import Head from 'next/head';
import { Inter } from '@next/font/google';

export default function AboutUs() {
  return (
    <>
      <Head>
        <title>About Us</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>About Us</h1>
        <p>this is the about us page</p>
      </main>
    </>
  );
}
