import Head from 'next/head';

import Layout from '../components/layout';

export default function Contact() {
  return (
    <>
      <Head>
        <title>About</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <h1>About Us</h1>
        <p>this is the about us page</p>
      </Layout>
    </>
  );
}
