import Head from 'next/head';
import Layout from '../components/layout';
import mainImage from '../public/homepage-cover.jpeg';

export default function Home() {
  return (
    <>
      <Head>
        <title>Luna Bakery KC</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout layoutImg={mainImage} imgAlt="Luna Bakery KC">
        <h1>An at-home micro sourdough bakery</h1>
        <p>this is a sans serif font</p>
      </Layout>
    </>
  );
}
