import Head from 'next/head';
import Navbar from '../components/navbar';
import Hero from '../sections/hero';
import Order from '../sections/order';
import About from '../sections/about';
import Contact from '../sections/contact';
import MeetMe from '../sections/meetMe';
import Footer from '../components/footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Luna Bakery KC</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* main page content and compontents */}
      <Navbar />
      <Hero />
      <Order />
      <About />
      <MeetMe />
      <Contact />
      <Footer />
    </>
  );
}
